---
- hosts: linuxmachines
  remote_user: ansible
  become: true
  tasks:
    - name: Instalar Apache
      yum:
        name: httpd
        state: latest
      notify: Restart Apache
    - name: Iniciar Apache
      service:
        name: httpd
        state: started
        enabled: yes
  handlers:
    - name: Restart Apache
      service: 
        name: httpd
        state: restarted