---
- hosts: all
  become: true
  vars:
    # The XKB keyboard model name.
    keyboard_model: pc104
    # The XKB keyboard layout name.
    keyboard_layout: es
    # The XKB keyboard variant components.
    keyboard_variant: ''
    # The XKB keyboard option components.
    keyboard_options: ''
    # The behavior of <BackSpace> and <Delete> keys.
    keyboard_backspace: guess
  tasks:
    - name: Install PreRequisites
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common
    - name: Add docker gpg key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
    - name: Add docker repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
    - name: Install docker engine
      package:
        name: "{{ item }}"
        state: latest
      loop:
        - docker-ce
        - docker-ce-cli
        - containerd.io
    - name: Install keyboard configuration
      package:
        name: keyboard-configuration
        state: present
    - name: Write keyboard configration
      template:
        src: keyboard.j2
        dest: /etc/default/keyboard
        force: yes
        owner: root
        group: root
        mode: 'u=rw,go=r'
    - name: Dpkg reconfigure Keyboard
      command: /usr/sbin/dpkg-reconfigure -f noninteractive keyboard-configuration
    - name: Add user vagrant to docker group
      user:
        name: vagrant
        group: docker
  
  # sudo usermod -aG docker $USER
  #notify:
  #  - dpkg-reconfigure keyboard-configuration docker run hello-world
        
        
        
        
        
        
        
        